### ISSUE TITLE
php apc version

### ISSUE THREAD

**Issue by Ragazzo** [odesk/phystrix#13]
Currently it looks that php apc is deprecated, in php 5.5.9-1 on ubuntu 14, extension is loaded by all its functions returns `false`, so currently it is not possible to work with phystrix. Do you have any plans on changing apc on anything else? Was talking to @lcf he said that using memcached / redis and other connection-like systems is not correct since main phystrix purpose is to handle partial failures, thus if system will have in itself components that can fail for example, over network reason, will not help for its main purpose - fault tolerance. So overall any ideas on this one?

**Comment by lcf** [comment]
@Ragazzo the apc functions Phystrix uses for storing information can still be installed with APCu http://pecl.php.net/package/APCu

The part that is deprecated is opcode cache because it is now built int. We do not rely on that part in Phystrix.

**Comment by sepn** [comment]
I also wanted to add that we are using Phystrix on php 5.5.9 on Ubuntu 14.04.

**Comment by Ragazzo** [comment]
@lcf correct, i am using `apcu` but all of its functions still return `false`. another thought maybe it is better to throw exception and fail fast when such things occur, because metrics are wrong and cant be used for anything? @sepn can you elaborate maybe on your installation and configuration of apc?

**Comment by Ragazzo** [comment]
ok, sorry, my bad, i did not remembered that for console it will not cache anything, only for fpm.

**Comment by Ragazzo** [comment]
also what would be your recommendations for using phystrix in console applications?

**Comment by Ragazzo** [comment]
ping @lcf so what about issue with console applications where usage of apc as cache here is not available?

**Comment by lcf** [comment]
@Ragazzo you can enable apc using apc.enable_cli = 1 http://php.net/manual/en/apc.configuration.php
does this help?

**Comment by Ragazzo** [comment]
not sure that it will help, since apc caching only within process space, thus since each console run is new process it cant be handled [correcty](http://stackoverflow.com/questions/10419546/apc-not-working-in-php-console). Do you use it in console or how you avoid such situations?

**Comment by lcf** [comment]
@Ragazzo sharing the same set of metrics between multiple running console applications is not supported out of the box, unfortunately. Due to APC cache limitations.

**Comment by bryanlatten** [comment]
@Ragazzo I bet we could quickly throw together a `shmop` adapter to implement nearly the same thing as APC: http://php.net/manual/en/book.shmop.php. Feels like a homework assignment from my college days. Only in a language that I hate less.

**Comment by bryanlatten** [comment]
I'll give it a shot over the next week - seems like a fun challenge

**Comment by Ragazzo** [comment]
@lcf indeed, ok then

@bryanlatten yes, it is not a problem to use other adapter, but the main difference here, is that it is not recommended to use other things that can fail over network partition (memcached, redis), yet shared memory can be used, but only as a metrics counter state storage. Of course it is wrong to use any other cache for `RequestLog`, `RequestCache`, `StateStorage` since you will run into several issues, one is that you are moving some part of code that actually can fail during partition to the code that should be fault tolerant by itself, and another that we found is difficult to deal with is that when several same type services are in play and one of the fail it can actually block other services that can run correctly. Overall since APC leaves only in process space it gives more flexibility to be true, due it will not affect other processes in wrong way, and of course there is a tradeoff that i listed above when asking how to use phystrix in console applications. 

> I bet we could quickly throw together a shmop adapter to implement nearly the same thing as APC:

yes

**Comment by bryanlatten** [comment]
@Ragazzo agreed. shmop is basically equivalent to APC(u), in that it is shared memory space for phystrix counters. I was simply trying to get us over the wall of FPM vs. CLI usage, since APC is not shared between CLI contexts

**Comment by Ragazzo** [comment]
yes, correct, if needed there are some more examples of shmop usage here [one](https://github.com/kriswallsmith/spork/tree/master/src/Spork) and [two](https://github.com/huyanping/simple-fork-php) if needed

**Comment by bryanlatten** [comment]
@Ragazzo gave shmop a try. fun little experiment, but overall causes a lot of headaches and isn't a viable replacement for apcu
- keys must be converted to system ID's (int or hex). I approached this by using the numeric value of the characters in a key segment (delimited by  `_`) added to major jumps in powers of 2. Causes a minefield of key assignments, but reasonably confident they couldn't clash
- [ ] shmop does not offer an atomic increment function. to implement manually,  you must lock a segment, read/add/write/release. this is extremely expensive performance-wise, but also forces us to deal with potential deadlocks
- [ ] shmop has issues with `0`. sometimes it thinks there is a value, sometimes it thinks the segment doesn't exist. unhelpful.
- [x] shmop does not offer segment expiration. this can be manually added, by encoding all segment payloads with an explicit expiration and checking/deleting on access. of all the issues, this one was mostly solved.
